create table cars (
  power integer,
  production_year integer,
  category_id bigint,
  id bigint generated by default as identity,
  price_id bigint unique,
  drive_type varchar(255) check (
    drive_type in ('FRONT', 'REAR', 'ALL_WHEEL')
  ),
  fuel_type varchar(255) check (
    fuel_type in (
      'PETROL', 'DIESEL', 'HYBRID', 'ELECTRIC'
    )
  ),
  make varchar(255),
  model varchar(255),
  status varchar(255) check (
    status in ('AVAILABLE', 'UNAVAILABLE')
  ),
  transmission_type varchar(255) check (
    transmission_type in ('MANUAL', 'AUTOMATIC')
  ),
  primary key (id)
);
create table categories (
  id bigint generated by default as identity,
  name varchar(255),
  primary key (id)
);
create table drivers (
  id bigint generated by default as identity,
  email varchar(255),
  first_name varchar(255),
  last_name varchar(255),
  phone_number varchar(255),
  primary key (id)
);
create table prices (
  for_day numeric(38, 2),
  for_two_to_four_days numeric(38, 2),
  for_week numeric(38, 2),
  id bigint generated by default as identity,
  primary key (id)
);
create table reservations (
  cost numeric(38, 2),
  end_date date,
  start_date date,
  car_id bigint,
  driver_id bigint unique,
  id bigint generated by default as identity,
  primary key (id),
  check (start_date <= end_date)
);
alter table
  if exists cars
add
  constraint FK310labqcoawyj05t4gvvfjbg9 foreign key (category_id) references categories on delete
set
  null;
alter table
  if exists cars
add
  constraint FK664urmyeywquq60jrbjo3llq3 foreign key (price_id) references prices;
alter table
  if exists reservations
add
  constraint FKkoxuu4vp8ex6mcc642sa11iyc foreign key (car_id) references cars on delete
set
  null;
alter table
  if exists reservations
add
  constraint FK7lgjeck6819ssjgdn5fj97rkj foreign key (driver_id) references drivers;
