create table cars (
  power integer,
  production_year integer,
  category_id bigint,
  id bigint generated by default as identity,
  price_id bigint unique,
  drive_type varchar(255) check (
    drive_type in ('FRONT', 'REAR', 'ALL_WHEEL')
  ),
  fuel_type varchar(255) check (
    fuel_type in (
      'PETROL', 'DIESEL', 'HYBRID', 'ELECTRIC'
    )
  ),
  make varchar(255),
  model varchar(255),
  status varchar(255) check (
    status in ('AVAILABLE', 'UNAVAILABLE')
  ),
  transmission_type varchar(255) check (
    transmission_type in ('MANUAL', 'AUTOMATIC')
  ),
  primary key (id)
);
create table categories (
  id bigint generated by default as identity,
  name varchar(255),
  primary key (id)
);
create table drivers (
  id bigint generated by default as identity,
  email varchar(255),
  first_name varchar(255),
  last_name varchar(255),
  phone_number varchar(255),
  primary key (id)
);
create table prices (
  for_day numeric(38, 2),
  for_two_to_four_days numeric(38, 2),
  for_week numeric(38, 2),
  id bigint generated by default as identity,
  primary key (id)
);
create table reservations (
  cost numeric(38, 2),
  end_date date,
  start_date date,
  car_id bigint,
  driver_id bigint unique,
  id bigint generated by default as identity,
  primary key (id),
  check (start_date <= end_date)
);
alter table
  if exists cars
add
  constraint FK310labqcoawyj05t4gvvfjbg9 foreign key (category_id) references categories on delete
set
  null;
alter table
  if exists cars
add
  constraint FK664urmyeywquq60jrbjo3llq3 foreign key (price_id) references prices;
alter table
  if exists reservations
add
  constraint FKkoxuu4vp8ex6mcc642sa11iyc foreign key (car_id) references cars on delete
set
  null;
alter table
  if exists reservations
add
  constraint FK7lgjeck6819ssjgdn5fj97rkj foreign key (driver_id) references drivers;


--Dodanie informacji o cenach wynajmu
INSERT INTO prices (for_day, for_two_to_four_days, for_week) VALUES
  (50.00, 45.00, 300.00),
  (60.00, 55.00, 350.00),
  (40.00, 35.00, 250.00),
  (55.00, 50.00, 320.00),
  (70.00, 65.00, 400.00),
  (55.00, 50.00, 320.00),
  (65.00, 60.00, 380.00),
  (45.00, 40.00, 280.00),
  (75.00, 70.00, 450.00);

-- Dodanie typów nadwozi (kategorii) samochodów
INSERT INTO categories (name) VALUES
  ('Sedan'),
  ('SUV'),
  ('Estate'),
  ('Hatchback'),
  ('Coupe');

-- Dodanie informacji o samochodach
INSERT INTO cars (power, production_year, category_id, price_id, drive_type, fuel_type, make, model, status, transmission_type) VALUES
  (150, 2022, 1, 1, 'FRONT', 'PETROL', 'Toyota', 'Camry', 'UNAVAILABLE', 'AUTOMATIC'),
  (120, 2020, 2, 2, 'REAR', 'DIESEL', 'Ford', 'Explorer', 'AVAILABLE', 'AUTOMATIC'),
  (130, 2021, 3, 3, 'FRONT', 'PETROL', 'Honda', 'Accord', 'AVAILABLE', 'AUTOMATIC'),
  (110, 2023, 4, 4, 'FRONT', 'HYBRID', 'Toyota', 'Prius', 'AVAILABLE', 'AUTOMATIC'),
  (160, 2022, 5, 5, 'ALL_WHEEL', 'PETROL', 'BMW', 'M4', 'AVAILABLE', 'AUTOMATIC'),
  (140, 2020, 2, 6, 'ALL_WHEEL', 'DIESEL', 'Audi', 'Q5', 'UNAVAILABLE', 'AUTOMATIC'),
  (110, 2021, 1, 7, 'FRONT', 'PETROL', 'Nissan', 'Altima', 'AVAILABLE', 'AUTOMATIC'),
  (95, 2022, 4, 8, 'FRONT', 'HYBRID', 'Toyota', 'Corolla', 'UNAVAILABLE', 'AUTOMATIC'),
  (120, 2020, 5, 9, 'FRONT', 'PETROL', 'Mercedes-Benz', 'C-Class', 'AVAILABLE', 'AUTOMATIC');

-- Dodanie informacji o kierowcach
INSERT INTO drivers (email, first_name, last_name, phone_number) VALUES
  ('john@example.com', 'John', 'Doe', '123456789'),
  ('jane@example.com', 'Jane', 'Smith', '987654321'),
  ('james@example.com', 'James', 'Johnson', '555123456'),
  ('emily@example.com', 'Emily', 'Brown', '555987654');

-- Dodanie informacji o rezerwacjach
INSERT INTO reservations (cost, start_date, end_date, car_id, driver_id) VALUES
  (150.00, '2023-10-15', '2023-10-20', 1, 1),
  (180.00, '2023-11-01', '2023-11-05', 2, 2),
  (160.00, '2023-12-01', '2023-12-10', 3, 3),
  (140.00, '2023-10-20', '2023-10-25', 4, 4);